CREATE TABLE IF NOT EXISTS property_market_transaction (
    transaction_id BIGINT NOT NULL AUTO_INCREMENT,
    source_id VARCHAR(180) NOT NULL,
    source_name VARCHAR(120) NOT NULL,
    lawd_cd VARCHAR(10) NOT NULL,
    deal_ymd VARCHAR(6) NOT NULL,
    apt_name VARCHAR(200) NOT NULL,
    neighborhood VARCHAR(120) NULL,
    jibun VARCHAR(80) NULL,
    road_name VARCHAR(200) NULL,
    deal_amount BIGINT NULL,
    area DECIMAL(10,2) NULL,
    floor_text VARCHAR(40) NULL,
    build_year INT NULL,
    deal_date DATE NULL,
    dealing_type VARCHAR(80) NULL,
    cancel_deal_yn VARCHAR(10) NULL,
    source_updated_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (transaction_id),
    UNIQUE KEY uk_property_market_source (source_id),
    KEY idx_property_market_region_month (lawd_cd, deal_ymd),
    KEY idx_property_market_apt (apt_name),
    KEY idx_property_market_deal_date (deal_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
